### ISSUE TITLE
No Devices Found - FR: IL

### ISSUE THREAD

**Issue by newoski** [jdeath/rd200v2#47]
Doesn't seem to find my RD200, which was manufactured in Jan 2025. Serial is IL09...

**Comment by jdeath** [comment]
I am not sure. Starting with `I` should be supported. I cannot test, since I do not have one. Others have said it worked. you can add some debug statements in config_flow.py and turn on debug in your home assistant config.yaml to figure out why not being found
```
logger:
  default: warning
  logs:
    custom_components.rd200_ble: debug
```
